langauge: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
  chrome: stable
dist: xenial
before_install:
  - yes | gem update --system --force
  - gem install bundler
script:
- yarn
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: WFY0lWvTQDz4u5Djvdo3GRQgufGfi7pBTyUH1bR+M1Kzm/NztQUsXNMsou++/8+q0KGILau52Y3pyr7Lgwdce8Cq0WKqdPv+12Wa8OkYhmlzCVOUj+Bi78d/yV34OcTkB+6louwx5Joa0s9PRuYPL99HfouyeowKPaIAllfJBayNrL2utZoibGrQBQGaLKldpmt3WVGYhJZGZQN02OYfym3mcrISei4sTkRmCZcHwkIEoZq2kDScoW97qQodp0Qi2jLUBL1pezlsqtpn20EwloogHEb9HbC6B6Amr1Cx+ScYmSvpwksStic3fHlitn+fZOV+o/AHzj36N5Dt2Fk0idcTI/DUBvJEpUXL7LfnGfpmK57A0O1a+Jkq/QsYe7M8uSXdBEQvR6xk3eSf1yGBLgFnkqCORs+C4eIhR8uv6z1LuIZcIJdkH/f93uuXk3maI2nbG9fX5YY1lRiZ2QzALLMydXWAdcaDvvZWrjOqjNMZhV8MYaTm6NxnId51HlQo5ircYRv8lwyRTKHsLOqgMG4Y0C+0Gd40F27cUs9JjDcqK9KuWVpEprieqqkDp4mT8/ew8q5XWOX1HA4XYHk9RTtWsmwkOVadaXi099pS2TWkOmRqcOJsK8zkxOD32FYRwyj5qX+u/KhtDa5wLKFR4Nbr9cUIxrEY3/eCgWdhy7s=
  app: dreamy-brownfield
  run: rails db:migrate
